# Generated by Django 3.0.6 on 2020-05-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('subregion', models.CharField(max_length=200)),
                ('population', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('gini', models.FloatField(blank=True, null=True)),
                ('flag', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Eco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('hdi', models.FloatField(blank=True, null=True)),
                ('gdpPerCapita', models.CharField(blank=True, max_length=50, null=True)),
                ('cropFootprint', models.FloatField(blank=True, null=True)),
                ('forestFootprint', models.FloatField(blank=True, null=True)),
                ('carbonFootprint', models.FloatField(blank=True, null=True)),
                ('ecoFootprint', models.FloatField(blank=True, null=True)),
                ('totalBiocapacity', models.FloatField(blank=True, null=True)),
                ('biocapacityReserve', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
    ]
